### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by bernaferrari** [cloudflare-design/color#11]
Title says it all. I wish I could drag images from the desktop or paste from clipboard and it automagically changed to 'Image' section and imported it.

**Comment by samjbmason** [comment]
Hey there,

Thanks for the suggestion, while I agree that would be cool it's a non trivial feature and also it's not too many more clicks to click on the tab and then click on upload.

Im going to close this but would be happy to look over a PR to this effect
